# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['__entry__.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('data', 'data'),
        ('background', 'background'),
    ],
    hiddenimports=[
        'PIL', 'PIL.Image', 'PIL.ImageTk',
        'PIL.ImageDraw', 'PIL.ImageFont',
        'matplotlib', 'matplotlib.backends',
        'matplotlib.backends.backend_tkagg',
        'matplotlib.backends.backend_agg',
        'matplotlib.backends._backend_tk',
        'matplotlib.font_manager',
        'matplotlib.ft2font',
        'numpy', 'numpy.core', 'numpy.lib',
        'numpy.random', 'numpy.linalg',
        'openpyxl', 'openpyxl.cell',
        'openpyxl.reader.excel', 'openpyxl.workbook',
        'openpyxl.writer.excel', 'openpyxl.styles',
        'openpyxl.utils', 'openpyxl.formatting',
        'openpyxl.chart',
        'pytz',
        'tkinter', 'tkinter.ttk',
        'tkinter.filedialog', 'tkinter.messagebox',
        'tkinter.simpledialog',
        'cycler', 'kiwisolver', 'dateutil',
        'pyparsing', 'packaging',
        'packaging.version', 'packaging.specifiers',
        'packaging.requirements',
        'random', 'time', 'datetime',
        # pandas 相关（FD_ELE_A3.py 需要）
        'pandas', 'pandas.core', 'pandas.io',
        'pandas.core.frame', 'pandas.core.series',
        'pandas.core.indexes', 'pandas.core.dtypes',
        'pandas.core.groupby', 'pandas.core.reshape',
        'pandas.core.window', 'pandas.core.strings',
        'pandas.core.arrays', 'pandas.core.sorting',
        'pandas.core.missing', 'pandas.core.common',
        'pandas._libs', 'pandas._libs.algos',
        'pandas._libs.indexing', 'pandas._libs.internals',
        'pandas._libs.lib', 'pandas._libs.ops',
        'pandas._libs.properties', 'pandas._libs.tslib',
        'pandas._libs.tslibs', 'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.timestamps',
        'pandas._libs.tslibs.timezones',
        'pandas._libs.tslibs.offsets',
        'pandas._libs.tslibs.parsing',
        'pandas._libs.tslibs.fields',
        'pandas._libs.tslibs.conversion',
        'pandas._libs.tslibs.period',
        'pandas._libs.tslibs.vectorized',
        'pandas._libs.tslibs.c_tz',
        'pandas._libs.tslibs.dtypes',
        # pandas 依赖
        'dateutil', 'pytz', 'numpy',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch', 'torchvision', 'tensorflow',
        'keras', 'PyQt5', 'PyQt6', 'PySide2',
        'PySide6', 'Django', 'flask', 'tornado',
        'aiohttp', 'boto3', 'botocore', 
        'opencv', 'cv2', 'pygame', 
        'scikit-learn', 'sklearn',
        'cryptography', 'paramiko', 'selenium',
        'beautifulsoup4', 'lxml',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyd = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyd,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='FD_ELE_A',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
