# -*- mode: python ; coding: utf-8 -*-
# 自动生成的spec文件 - 包含所有DLL依赖
# 生成时间: 2025-12-23 09:45:07

block_cipher = None

a = Analysis(
    ['FD_MGS_A_Main.py'],
    pathex=[],
    binaries=[
        ('dll_for_pack/api-ms-win-core-console-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-datetime-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-debug-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-errorhandling-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-fibers-l1-1-1.dll', '.'),
        ('dll_for_pack/api-ms-win-core-file-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-file-l1-2-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-file-l2-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-handle-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-heap-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-interlocked-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-kernel32-legacy-l1-1-1.dll', '.'),
        ('dll_for_pack/api-ms-win-core-libraryloader-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-localization-l1-2-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-memory-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-namedpipe-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-path-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-processenvironment-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-processthreads-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-processthreads-l1-1-1.dll', '.'),
        ('dll_for_pack/api-ms-win-core-profile-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-rtlsupport-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-string-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-synch-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-synch-l1-2-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-sysinfo-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-sysinfo-l1-2-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-timezone-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-core-util-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-convert-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-environment-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-filesystem-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-heap-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-locale-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-math-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-multibyte-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-runtime-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-stdio-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-string-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-time-l1-1-0.dll', '.'),
        ('dll_for_pack/api-ms-win-crt-utility-l1-1-0.dll', '.'),
    ],
    datas=[
        ('FD-MGS-A.ui', '.'),
        ('Ui_FD_MGS_A.py', '.'),
    ],
    hiddenimports=[
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.uic',
        'matplotlib',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.figure',
        'matplotlib.pyplot',
        'numpy',
        'serial',
        'serial.tools.list_ports',
        'importlib_resources.trees',  # 补充缺失的隐藏导入，避免运行时找不到
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='FD-MGS-A',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 不显示控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
